# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

# Extension for block renders (order status and profile blocks)
[[extensions]]
name = "Loyco Customer Account Blocks"
handle = "loyco-customer-account-blocks"
uid = "d7acdbc4-67b3-3c7a-55c4-415a168b5ff96a003d97"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"

[[extensions.targeting]]
module = "./src/LoyaltyOverviewBlock.jsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
api_access = true
network_access = true

# Extension for page render (Loyco Club page)
[[extensions]]
name = "Loyco Customer Account Page"
handle = "loyco-customer-account-page"
uid = "32dbe592-47b6-fca2-3dca-4180c443588b05414677"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/LoyaltyPage.jsx"
target = "customer-account.page.render"

[extensions.capabilities]
api_access = true
network_access = true
